# This workflow will do a clean install of node dependencies and then compile the needed
# JSON files for the blog.

name: Generate Blog Content JSON

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Checkout gh-pages branch in a subfolder.
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      run: |
        rm -rf gh-pages
        git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
        cd gh-pages
        rm *.json
        git config user.name "Github Action"
        git checkout -b gh-pages origin/gh-pages
        cd -
    - name: Generate the content
      run: npm run generate
    - name: Commit the generated files
      run: |
        cd gh-pages
        git add *.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Generated new content"; git push origin master)
        git push